budget/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('', views.project_list, name='list'),
    path('add-budget', views.BudgetCreateView.as_view(), name='add-budget'),
    path('<slug:project_slug>', views.project_detail, name='detail'),
]

budgetapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('budget.urls')),
    path('admin/', admin.site.urls),
]

budget/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.utils.text import slugify


class Budget(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    budget = models.IntegerField()

    def __str__(self):
        return self.name


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Budget, self).save(*args, **kwargs)

    def budget_left(self):
        expense_list = Expense.objects.filter(budget=self)
        total_expense_amount = 0

        for expense in expense_list:
            total_expense_amount += expense.amount

        return self.budget - total_expense_amount
    

    
class Users(models.Model):
    budget = models.ForeignKey(Budget, on_delete=CASCADE, related_name='users')
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name   

    def user_total(self):
        expense_list = Expense.objects.filter(budget=self.budget)
        user_expense = 0
        user_total = self.budget.budget // 2

        for expense in expense_list:
            if self.id == expense.user.id:
                user_expense += expense.amount

        return user_total - user_expense


class Category(models.Model):
    budget = models.ForeignKey(Budget, on_delete=CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Expense(models.Model):
    budget = models.ForeignKey(Budget, on_delete=models.CASCADE, related_name='expenses')
    description = models.CharField(max_length=200)
    amount = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=CASCADE)
    date = models.DateField()
    # date = models.CharField(max_length=10)
    user = models.ForeignKey(Users, on_delete=models.CASCADE, related_name='users')

    def __str__(self):
        return self.description

budget/forms.py
from django import forms


class ExpenseForm(forms.Form):
    date = forms.DateField()
    description = forms.CharField()
    amount = forms.IntegerField()
    category = forms.CharField()
    user = forms.CharField()

budget/views.py
from budget.forms import ExpenseForm
from django.http.response import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from .models import Budget, Category, Expense, Users
from django.views.generic import CreateView
from django.utils.text import slugify
from .forms import ExpenseForm
import json


def project_list (request):
    return render(request, 'budget/project_list.html')

        

def project_detail (request, project_slug):
    budget = get_object_or_404(Budget, slug=project_slug)

    if request.method == 'GET':
        category_list = Category.objects.filter(budget=budget)
        users_list = Users.objects.filter(budget=budget)
        return render(request, 'budget/project_detail.html', {'budget':budget, 'expense_list': budget.expenses.all(), 'category_list': category_list, 'users_list': users_list})

    elif request.method == 'POST':
        form = ExpenseForm(request.POST)

        if form.is_valid():
            date = form.cleaned_data['date']
            description = form.cleaned_data['description']
            amount = form.cleaned_data['amount']
            category_name = form.cleaned_data['category']
            user_name = form.cleaned_data['user']

            category = get_object_or_404(Category, budget=budget, name=category_name)
            user = get_object_or_404(Users, budget=budget, name=user_name)

            Expense.objects.create(
                budget = budget,    
                date = date,
                description = description,
                amount =  amount,
                category = category,
                user = user
    
            ).save()

    elif request.method == 'DELETE':
        id = json.loads(request.body)['id']
        expense = get_object_or_404(Expense, id=id)
        expense.delete()

        return HttpResponse('')

    return HttpResponseRedirect(project_slug)


class BudgetCreateView(CreateView):
    model = Budget
    template_name = 'budget/add-budget.html'
    
    fields = ('name', 'budget')


    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()

        categories = self.request.POST['categoriesString'].split(',')
        for category in categories:
            Category.objects.create(
                budget = Budget.objects.get(id=self.object.id),
                name = category
            ).save()
            

        users = self.request.POST['usersString'].split(',')
        for user in users:
            Users.objects.create(
                budget = Budget.objects.get(id=self.object.id),
                name = user
            ).save()   
    
        return HttpResponseRedirect(self.get_success_url())


    def get_success_url(self):
        return slugify(self.request.POST['name'])

budget/templates/budget/add-budget.html
{% extends 'budget/base.html' %}
{% load static %}
{% block content %}

<div id="add_budget" class="container">
    <form action="" method="POST">
        
        {% csrf_token %}
        <label for="id_name">Month name:</label>
        <input type="text" name="name" id="id_name">
        <label for="id_budget">Total monthly budget:</label>
        <input type="number" name="budget" id="id_budget">
        <label for="categoryInput">Expense categories (hit enter after every category)</label>
        <input type="text" name="categoryInput" id="categoryInput">
        <input type="hidden" name="categoriesString">

        <ul id="categoriesContainer">
            
        </ul>

        <label for="userInput">Add users (hit enter after every user name)</label>
        <input type="text" name="userInput" id="userInput">
        <input type="hidden" name="usersString">

        <ul id="usersContainer">
           
        </ul>

        <button type="submit" class="btn">Start Budget</button>


    </form>

</div>

<script src="{% static 'js/script.js' %}"></script>

{% endblock %}

budget/templates/budget/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Monthly Budget</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!-- for datepicker -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <script>
        $( function() {
          $( "#date" ).datepicker();
        } );
        </script>

</head>
<body>

    {% block content %}

    {% endblock %}
    
</body>
</html>

budget/templates/budget/project_detail.html
{% extends 'budget/base.html' %}
{% block content %}

<div class="container">

    <section class="section section-stats">
        <div class="row">

            <div class="col s12 m4 8">
                <div class="card-panel">
                    <h6><strong>Total Budget</strong></h6>
                    <h3>Rs {{ budget.budget}} </h3>
                </div>
            </div>

            <div class="col s12 m4 8">
                <div class="card-panel">
                    <h6><strong>Remaining budget</strong></h6>
                    {% if budget.budget_left > 0 %}
                    <h3 class='green-text'>Rs {{ budget.budget_left }}</h3>
                    {% else %}
                    <h3 class='red-text'>Rs {{ budget.budget_left }}</h3>
                    {% endif %}
                </div>
            </div>

            {% for user in users_list %}

            <div class="col s12 m4 8">
                <div class="card-panel">
                    <h6><strong>{{ user.name }} remaining bal</strong></h6>
                    
                    <h3>Rs {{ user.user_total }}</h3>
                </div>
            </div>

            {% endfor %}

        </div>
    </section>

    <section class="section section-expenses">
        <div class='row'>
            <button class="btn waves-effect right modal-trigger" href="#expenseModal">
                <i class="material-icons white-text left">add_circle</i>
                Add expense</button>
        </div>

        <ul class="z-depth-1">

            {% for expense in expense_list %}

            <li>
                <div class="card-panel z-depth-0 expense">
                    <div class="row">
                        <div class="col l4">
                            <span class="title">{{ expense.date }}</span>
                        </div>

                        <div class="col l3">
                            <span class="title">{{ expense.description }}</span>
                        </div>

                        <div class="col l2">
                            <span class="title">Rs {{ expense.amount }}</span>
                        </div>

                        <div class="col l1">
                            <span class="title">{{ expense.user }}</span>
                        </div>

                        <a onclick="deleteExpense(this)" data-id="{{ expense.id }}">
                            <i class="material-icons red-text right">close</i>
                        </a>
                    </div>
                </div>
            </li>

            {% endfor %}

        </ul>
    </section>

    </div> 

</div>

<div id="expenseModal" class="modal">

    <div class="model-content">
        <h4>Add Expense</h4>

        <form method="POST">
            
            {% csrf_token %}
            
            <label for="date">Date</label>
            <input name="date" id="date">

            <label for="description">Description</label>
            <input name="description" id="description">

            <label for="amount">Amount</label>
            <input name="amount" id="amount">

            <select name="category">
                {% for category in category_list %}
                    <option>{{ category.name }}</option>
                {% endfor %}
            </select>

            <select name="user">
                {% for user in users_list %}
                    <option>{{ user.name }}</option>
                {% endfor %}
            </select>

            <button type="submit" class="btn">Add</button>

        </form>
    </div>
</div>

<script>
    var elems = document.querySelectorAll('.modal')
    var instances = M.Modal.init(elems)

    var elems = document.querySelectorAll('select')
    var instances = M.FormSelect.init(elems)
    

    function deleteExpense(e){

        let id = e.dataset.id
        e.closest('li').remove()

        fetch('', {
            method: 'DELETE',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            },
            body: JSON.stringify({
                'id': id
            }),
            credentials: 'same-origin',
        })
        window.location.reload();
    }
</script> 


{% endblock %}

budget/templates/budget/project_list.html
{% extends 'budget/base.html' %}
{% block content %}

<div class="container">

    <div class="noproject-wrapper center">
        <h3 class="">Let's start budgeting!</h3>
        <a href="{% url 'add-budget' %}" class="btn-large green">
            <i class="material-icons white-text left">add_circle</i>
            <span class="bold">Add Budget</span>
        </a>
    </div>

</div>

{% endblock %}